### ISSUE TITLE
Ide/önskan

### ISSUE THREAD

**Issue by flopp999** [robinostlund/homeassistant-svk-mimer#8]
Få en device som är summan av FCR-D Up och Down.
Det är ju väldigt enkelt med några rader i HA som man kan göra själv men du kanske kan lägga till detta?
Såg att det finns today_sum som attribute men hade man kunnat få dessa två *_sum som en egen Entity?

**Comment by robinostlund** [comment]
Bra idé ska kika :)

**Comment by robinostlund** [comment]
@flopp999 vet du om det är möjligt att bara subscriba på FCR-D Ner? Eller blir det automatiskt ner och upp? För config flödet skapar nu olika sensorer beroende på vilken tjänst man är med i.

Så jag undrar om jag kan merga subscribing fcr_d_down och fcr_d_up till subscribing_fcr_d?

**Comment by robinostlund** [comment]
@flopp999 så nu borde sensorn finnas med i senaste versionen, dock så gjorde jag om config flödet lite så du behöver force refresha home assistant guit och sen köra configure på integrationen och fylla i rätt värden igen :)

**Comment by flopp999** [comment]
> @flopp999 vet du om det är möjligt att bara subscriba på FCR-D Ner? Eller blir det automatiskt ner och upp? För config flödet skapar nu olika sensorer beroende på vilken tjänst man är med i.
> 
> Så jag undrar om jag kan merga subscribing fcr_d_down och fcr_d_up till subscribing_fcr_d?

Jag tror det är Down och Up som Checkwatt gör men man kan styra bara en av dom om den som styr vill.
Såg att du behållt Down och Up 👍

**Comment by flopp999** [comment]
> @flopp999 så nu borde sensorn finnas med i senaste versionen, dock så gjorde jag om config flödet lite så du behöver force refresha home assistant guit och sen köra configure på integrationen och fylla i rätt värden igen :)

Tryckte Configure och allt var korrekt ifyllt utan att jag behövde göra något.
FCD-D var ifyllt och den kom ihåg mina kW och % fee
